from hyperon import MeTTa, E, S, ValueAtom

def initialize_knowledge_graph(metta: MeTTa):

    metta.space().add_atom(E(S("symptom"), S("fever"), S("flu")))
    metta.space().add_atom(E(S("treatment"), S("diabetes+flu"), ValueAtom("insulin,antiviral,rest")))
    metta.space().add_atom(E(S("side_effect"), S("insulin,antiviral,rest"), ValueAtom("hypoglycemia,nausea")))
    metta.space().add_atom(E(S("symptom"), S("headache,dizziness,nausea"), S("hypertension+migraine")))
    metta.space().add_atom(E(S("treatment"), S("hypertension+migraine"), ValueAtom("beta-blockers,sumatriptan,rest")))
    metta.space().add_atom(E(S("side_effect"), S("beta-blockers,sumatriptan,rest"), ValueAtom("fatigue,drowsiness")))
    metta.space().add_atom(E(S("symptom"), S("shortness of breath,chest pain,fever"), S("asthma+pneumonia")))
    metta.space().add_atom(E(S("treatment"), S("asthma+pneumonia"), ValueAtom("antibiotics,bronchodilators,oxygen")))
    metta.space().add_atom(E(S("side_effect"), S("antibiotics,bronchodilators,oxygen"), ValueAtom("stomach upset,tremors")))
    metta.space().add_atom(E(S("symptom"), S("sadness,worry,insomnia"), S("depression+anxiety")))
    metta.space().add_atom(E(S("treatment"), S("depression+anxiety"), ValueAtom("sertraline,therapy,meditation")))
    metta.space().add_atom(E(S("side_effect"), S("sertraline,therapy,meditation"), ValueAtom("nausea,initial discomfort")))
    metta.space().add_atom(E(S("symptom"), S("weakness,speech difficulty,chest pain"), S("heart disease+stroke")))
    metta.space().add_atom(E(S("treatment"), S("heart disease+stroke"), ValueAtom("blood thinners,physiotherapy,aspirin")))
    metta.space().add_atom(E(S("side_effect"), S("blood thinners,physiotherapy,aspirin"), ValueAtom("bleeding,muscle soreness")))
    metta.space().add_atom(E(S("symptom"), S("joint pain,stiffness,bone pain"), S("arthritis+osteoporosis")))
    metta.space().add_atom(E(S("treatment"), S("arthritis+osteoporosis"), ValueAtom("calcium,NSAIDs,physiotherapy")))
    metta.space().add_atom(E(S("side_effect"), S("calcium,NSAIDs,physiotherapy"), ValueAtom("constipation,stomach irritation")))
    metta.space().add_atom(E(S("symptom"), S("runny nose,sore throat,mild fever"), S("common cold")))
    metta.space().add_atom(E(S("treatment"), S("common cold"), ValueAtom("rest,fluids,acetaminophen")))
    metta.space().add_atom(E(S("side_effect"), S("rest,fluids,acetaminophen"), ValueAtom("")))
    metta.space().add_atom(E(S("symptom"), S("chronic cough,wheezing,mucus"), S("COPD+bronchitis")))
    metta.space().add_atom(E(S("treatment"), S("COPD+bronchitis"), ValueAtom("inhalers,antibiotics,pulmonary rehab")))
    metta.space().add_atom(E(S("side_effect"), S("inhalers,antibiotics,pulmonary rehab"), ValueAtom("dry mouth,diarrhea")))
    metta.space().add_atom(E(S("symptom"), S("burning urination,back pain,fever"), S("kidney disease+UTI")))
    metta.space().add_atom(E(S("treatment"), S("kidney disease+UTI"), ValueAtom("antibiotics,hydration,dialysis")))
    metta.space().add_atom(E(S("side_effect"), S("antibiotics,hydration,dialysis"), ValueAtom("nausea,electrolyte imbalance")))
    metta.space().add_atom(E(S("symptom"), S("vomiting,diarrhea,abdominal pain"), S("gastroenteritis")))
    metta.space().add_atom(E(S("treatment"), S("gastroenteritis"), ValueAtom("oral rehydration,probiotics,bland diet")))
    metta.space().add_atom(E(S("side_effect"), S("oral rehydration,probiotics,bland diet"), ValueAtom("")))
    metta.space().add_atom(E(S("symptom"), S("jaundice,fatigue,abdominal swelling"), S("liver disease+hepatitis")))
    metta.space().add_atom(E(S("treatment"), S("liver disease+hepatitis"), ValueAtom("antivirals,liver transplant,dietary changes")))
    metta.space().add_atom(E(S("side_effect"), S("antivirals,liver transplant,dietary changes"), ValueAtom("immunosuppression,nausea")))
    metta.space().add_atom(E(S("symptom"), S("hair loss,nausea,fatigue"), S("cancer")))
    metta.space().add_atom(E(S("treatment"), S("cancer"), ValueAtom("chemotherapy,radiation,surgery")))
    metta.space().add_atom(E(S("side_effect"), S("chemotherapy,radiation,surgery"), ValueAtom("hair loss,nausea,fatigue")))
    metta.space().add_atom(E(S("symptom"), S("weight gain,fatigue,cold sensitivity"), S("hypothyroidism")))
    metta.space().add_atom(E(S("treatment"), S("hypothyroidism"), ValueAtom("levothyroxine,diet modification,exercise")))
    metta.space().add_atom(E(S("side_effect"), S("levothyroxine,diet modification,exercise"), ValueAtom("palpitations,insomnia")))
    metta.space().add_atom(E(S("symptom"), S("rash,itching,swelling"), S("allergic reaction")))
    metta.space().add_atom(E(S("treatment"), S("allergic reaction"), ValueAtom("antihistamines,steroids,epinephrine")))
    metta.space().add_atom(E(S("side_effect"), S("antihistamines,steroids,epinephrine"), ValueAtom("drowsiness,increased appetite")))
    metta.space().add_atom(E(S("symptom"), S("convulsions,loss of consciousness,confusion"), S("epilepsy")))
    metta.space().add_atom(E(S("treatment"), S("epilepsy"), ValueAtom("anticonvulsants,lifestyle changes,surgery")))
    metta.space().add_atom(E(S("side_effect"), S("anticonvulsants,lifestyle changes,surgery"), ValueAtom("dizziness,cognitive effects")))
    metta.space().add_atom(E(S("symptom"), S("nausea,vomiting,fatigue"), S("pregnancy")))
    metta.space().add_atom(E(S("treatment"), S("pregnancy"), ValueAtom("prenatal vitamins,ginger,small meals")))
    metta.space().add_atom(E(S("side_effect"), S("prenatal vitamins,ginger,small meals"), ValueAtom("constipation")))
    metta.space().add_atom(E(S("symptom"), S("widespread pain,fatigue,sleep disturbance"), S("fibromyalgia")))
    metta.space().add_atom(E(S("treatment"), S("fibromyalgia"), ValueAtom("pregabalin,exercise,sleep hygiene")))
    metta.space().add_atom(E(S("side_effect"), S("pregabalin,exercise,sleep hygiene"), ValueAtom("dizziness,weight gain")))
    metta.space().add_atom(E(S("symptom"), S("vomiting,diarrhea,fever"), S("food poisoning")))
    metta.space().add_atom(E(S("treatment"), S("food poisoning"), ValueAtom("hydration,rest,electrolyte replacement")))
    metta.space().add_atom(E(S("side_effect"), S("hydration,rest,electrolyte replacement"), ValueAtom("")))
    metta.space().add_atom(E(S("symptom"), S("facial pain,nasal congestion,headache"), S("sinusitis")))
    metta.space().add_atom(E(S("treatment"), S("sinusitis"), ValueAtom("antibiotics,decongestants,nasal irrigation")))
    metta.space().add_atom(E(S("side_effect"), S("antibiotics,decongestants,nasal irrigation"), ValueAtom("stomach upset,jitteriness")))
    metta.space().add_atom(E(S("symptom"), S("fatigue,weakness,pale skin"), S("anemia")))
    metta.space().add_atom(E(S("treatment"), S("anemia"), ValueAtom("iron supplements,dietary changes,vitamin B12")))
    metta.space().add_atom(E(S("side_effect"), S("iron supplements,dietary changes,vitamin B12"), ValueAtom("constipation,stomach upset")))
    metta.space().add_atom(E(S("symptom"), S("chest pain,shortness of breath,fatigue"), S("diabetes+heart disease")))
    metta.space().add_atom(E(S("treatment"), S("diabetes+heart disease"), ValueAtom("metformin,ACE inhibitors,cardiac rehab")))
    metta.space().add_atom(E(S("side_effect"), S("metformin,ACE inhibitors,cardiac rehab"), ValueAtom("gastrointestinal upset,dry cough")))
    metta.space().add_atom(E(S("symptom"), S("joint swelling,morning stiffness,fatigue"), S("rheumatoid arthritis")))
    metta.space().add_atom(E(S("treatment"), S("rheumatoid arthritis"), ValueAtom("methotrexate,biologics,physiotherapy")))
    metta.space().add_atom(E(S("side_effect"), S("methotrexate,biologics,physiotherapy"), ValueAtom("liver toxicity,infection risk")))
    metta.space().add_atom(E(S("symptom"), S("tremor,rigidity,slow movement"), S("Parkinson disease")))
    metta.space().add_atom(E(S("treatment"), S("Parkinson disease"), ValueAtom("levodopa,dopamine agonists,deep brain stimulation")))
    metta.space().add_atom(E(S("side_effect"), S("levodopa,dopamine agonists,deep brain stimulation"), ValueAtom("dyskinesia,hallucinations")))
    metta.space().add_atom(E(S("symptom"), S("memory loss,confusion,disorientation"), S("Alzheimer disease")))
    metta.space().add_atom(E(S("treatment"), S("Alzheimer disease"), ValueAtom("donepezil,memantine,cognitive therapy")))
    metta.space().add_atom(E(S("side_effect"), S("donepezil,memantine,cognitive therapy"), ValueAtom("nausea,diarrhea")))
    metta.space().add_atom(E(S("symptom"), S("excessive thirst,frequent urination,weight loss"), S("type 1 diabetes")))
    metta.space().add_atom(E(S("treatment"), S("type 1 diabetes"), ValueAtom("insulin therapy,blood glucose monitoring,diet control")))
    metta.space().add_atom(E(S("side_effect"), S("insulin therapy,blood glucose monitoring,diet control"), ValueAtom("hypoglycemia,weight gain")))
    metta.space().add_atom(E(S("symptom"), S("bone pain,fractures,kidney stones"), S("osteoporosis+hyperparathyroidism")))
    metta.space().add_atom(E(S("treatment"), S("osteoporosis+hyperparathyroidism"), ValueAtom("bisphosphonates,parathyroidectomy,calcium")))
    metta.space().add_atom(E(S("side_effect"), S("bisphosphonates,parathyroidectomy,calcium"), ValueAtom("jaw necrosis,hypocalcemia")))
    metta.space().add_atom(E(S("symptom"), S("muscle weakness,double vision,difficulty swallowing"), S("myasthenia gravis")))
    metta.space().add_atom(E(S("treatment"), S("myasthenia gravis"), ValueAtom("pyridostigmine,immunosuppressants,thymectomy")))
    metta.space().add_atom(E(S("side_effect"), S("pyridostigmine,immunosuppressants,thymectomy"), ValueAtom("muscle cramps,infection risk")))
    metta.space().add_atom(E(S("symptom"), S("skin lesions,joint pain,fatigue"), S("lupus")))
    metta.space().add_atom(E(S("treatment"), S("lupus"), ValueAtom("hydroxychloroquine,corticosteroids,immunosuppressants")))
    metta.space().add_atom(E(S("side_effect"), S("hydroxychloroquine,corticosteroids,immunosuppressants"), ValueAtom("retinal toxicity,osteoporosis")))
    metta.space().add_atom(E(S("symptom"), S("abdominal pain,diarrhea,weight loss"), S("Crohn disease")))
    metta.space().add_atom(E(S("treatment"), S("Crohn disease"), ValueAtom("infliximab,mesalamine,surgery")))
    metta.space().add_atom(E(S("side_effect"), S("infliximab,mesalamine,surgery"), ValueAtom("infection risk,liver toxicity")))
    metta.space().add_atom(E(S("symptom"), S("bloody stool,abdominal cramping,urgency"), S("ulcerative colitis")))
    metta.space().add_atom(E(S("treatment"), S("ulcerative colitis"), ValueAtom("sulfasalazine,steroids,colectomy")))
    metta.space().add_atom(E(S("side_effect"), S("sulfasalazine,steroids,colectomy"), ValueAtom("nausea,mood changes")))
    metta.space().add_atom(E(S("symptom"), S("mood swings,mania,depression"), S("bipolar disorder")))
    metta.space().add_atom(E(S("treatment"), S("bipolar disorder"), ValueAtom("lithium,mood stabilizers,therapy")))
    metta.space().add_atom(E(S("side_effect"), S("lithium,mood stabilizers,therapy"), ValueAtom("tremor,weight gain")))
    metta.space().add_atom(E(S("symptom"), S("hallucinations,delusions,disorganized thinking"), S("schizophrenia")))
    metta.space().add_atom(E(S("treatment"), S("schizophrenia"), ValueAtom("antipsychotics,cognitive therapy,social support")))
    metta.space().add_atom(E(S("side_effect"), S("antipsychotics,cognitive therapy,social support"), ValueAtom("tardive dyskinesia,sedation")))
    metta.space().add_atom(E(S("symptom"), S("panic attacks,fear,avoidance"), S("panic disorder")))
    metta.space().add_atom(E(S("treatment"), S("panic disorder"), ValueAtom("benzodiazepines,CBT,SSRIs")))
    metta.space().add_atom(E(S("side_effect"), S("benzodiazepines,CBT,SSRIs"), ValueAtom("dependency,initial anxiety")))
    metta.space().add_atom(E(S("symptom"), S("intrusive thoughts,compulsions,anxiety"), S("OCD")))
    metta.space().add_atom(E(S("treatment"), S("OCD"), ValueAtom("fluoxetine,exposure therapy,clomipramine")))
    metta.space().add_atom(E(S("side_effect"), S("fluoxetine,exposure therapy,clomipramine"), ValueAtom("sexual dysfunction,dry mouth")))
    metta.space().add_atom(E(S("symptom"), S("flashbacks,nightmares,hypervigilance"), S("PTSD")))
    metta.space().add_atom(E(S("treatment"), S("PTSD"), ValueAtom("sertraline,EMDR therapy,prazosin")))
    metta.space().add_atom(E(S("side_effect"), S("sertraline,EMDR therapy,prazosin"), ValueAtom("insomnia,emotional processing")))
    metta.space().add_atom(E(S("symptom"), S("inattention,hyperactivity,impulsivity"), S("ADHD")))
    metta.space().add_atom(E(S("treatment"), S("ADHD"), ValueAtom("methylphenidate,behavioral therapy,atomoxetine")))
    metta.space().add_atom(E(S("side_effect"), S("methylphenidate,behavioral therapy,atomoxetine"), ValueAtom("appetite suppression,insomnia")))
    metta.space().add_atom(E(S("symptom"), S("tics,vocalizations,repetitive movements"), S("Tourette syndrome")))
    metta.space().add_atom(E(S("treatment"), S("Tourette syndrome"), ValueAtom("haloperidol,behavioral intervention,botulinum toxin")))
    metta.space().add_atom(E(S("side_effect"), S("haloperidol,behavioral intervention,botulinum toxin"), ValueAtom("sedation,muscle weakness")))
    metta.space().add_atom(E(S("symptom"), S("seizures,developmental delay,regression"), S("epilepsy+autism")))
    metta.space().add_atom(E(S("treatment"), S("epilepsy+autism"), ValueAtom("valproate,behavioral therapy,special education")))
    metta.space().add_atom(E(S("side_effect"), S("valproate,behavioral therapy,special education"), ValueAtom("hair loss,weight gain")))
    metta.space().add_atom(E(S("symptom"), S("multiple sclerosis,fatigue,weakness"), S("multiple sclerosis")))
    metta.space().add_atom(E(S("treatment"), S("multiple sclerosis"), ValueAtom("interferon,corticosteroids,physiotherapy")))
    metta.space().add_atom(E(S("side_effect"), S("interferon,corticosteroids,physiotherapy"), ValueAtom("flu-like symptoms,osteoporosis")))
    metta.space().add_atom(E(S("symptom"), S("headache,visual disturbances,seizures"), S("brain tumor")))
    metta.space().add_atom(E(S("treatment"), S("brain tumor"), ValueAtom("surgery,radiation therapy,chemotherapy")))
    metta.space().add_atom(E(S("side_effect"), S("surgery,radiation therapy,chemotherapy"), ValueAtom("cognitive impairment,hair loss")))
    metta.space().add_atom(E(S("symptom"), S("chest pain,shortness of breath,palpitations"), S("atrial fibrillation")))
    metta.space().add_atom(E(S("treatment"), S("atrial fibrillation"), ValueAtom("warfarin,beta-blockers,cardioversion")))
    metta.space().add_atom(E(S("side_effect"), S("warfarin,beta-blockers,cardioversion"), ValueAtom("bleeding,bradycardia")))
    metta.space().add_atom(E(S("symptom"), S("leg swelling,shortness of breath,fatigue"), S("heart failure")))
    metta.space().add_atom(E(S("treatment"), S("heart failure"), ValueAtom("ACE inhibitors,diuretics,cardiac rehab")))
    metta.space().add_atom(E(S("side_effect"), S("ACE inhibitors,diuretics,cardiac rehab"), ValueAtom("hyperkalemia,dehydration")))
    metta.space().add_atom(E(S("symptom"), S("leg pain,cramping,coldness"), S("peripheral artery disease")))
    metta.space().add_atom(E(S("treatment"), S("peripheral artery disease"), ValueAtom("cilostazol,exercise therapy,angioplasty")))
    metta.space().add_atom(E(S("side_effect"), S("cilostazol,exercise therapy,angioplasty"), ValueAtom("headache,muscle pain")))
    metta.space().add_atom(E(S("symptom"), S("severe headache,neck stiffness,nausea"), S("subarachnoid hemorrhage")))
    metta.space().add_atom(E(S("treatment"), S("subarachnoid hemorrhage"), ValueAtom("surgery,nimodipine,bed rest")))
    metta.space().add_atom(E(S("side_effect"), S("surgery,nimodipine,bed rest"), ValueAtom("vasospasm,hypotension")))
    metta.space().add_atom(E(S("symptom"), S("chest tightness,wheezing,cough"), S("asthma+allergies")))
    metta.space().add_atom(E(S("treatment"), S("asthma+allergies"), ValueAtom("inhaled steroids,antihistamines,allergy shots")))
    metta.space().add_atom(E(S("side_effect"), S("inhaled steroids,antihistamines,allergy shots"), ValueAtom("oral thrush,drowsiness")))
    metta.space().add_atom(E(S("symptom"), S("persistent cough,blood in sputum,weight loss"), S("lung cancer")))
    metta.space().add_atom(E(S("treatment"), S("lung cancer"), ValueAtom("surgery,chemotherapy,radiation")))
    metta.space().add_atom(E(S("side_effect"), S("surgery,chemotherapy,radiation"), ValueAtom("infection,neuropathy")))
    metta.space().add_atom(E(S("symptom"), S("sleep apnea,snoring,daytime fatigue"), S("sleep apnea")))
    metta.space().add_atom(E(S("treatment"), S("sleep apnea"), ValueAtom("CPAP,weight loss,surgery")))
    metta.space().add_atom(E(S("side_effect"), S("CPAP,weight loss,surgery"), ValueAtom("nasal congestion,dry mouth")))
    metta.space().add_atom(E(S("symptom"), S("chest pain,fever,productive cough"), S("pneumonia+COPD")))
    metta.space().add_atom(E(S("treatment"), S("pneumonia+COPD"), ValueAtom("antibiotics,bronchodilators,oxygen therapy")))
    metta.space().add_atom(E(S("side_effect"), S("antibiotics,bronchodilators,oxygen therapy"), ValueAtom("diarrhea,tremors")))
    metta.space().add_atom(E(S("symptom"), S("chest pain,shortness of breath,rapid pulse"), S("pulmonary embolism")))
    metta.space().add_atom(E(S("treatment"), S("pulmonary embolism"), ValueAtom("heparin,warfarin,thrombolytics")))
    metta.space().add_atom(E(S("side_effect"), S("heparin,warfarin,thrombolytics"), ValueAtom("bleeding,heparin-induced thrombocytopenia")))
    metta.space().add_atom(E(S("symptom"), S("difficulty breathing,chest pain,collapsed lung"), S("pneumothorax")))
    metta.space().add_atom(E(S("treatment"), S("pneumothorax"), ValueAtom("chest tube,surgery,observation")))
    metta.space().add_atom(E(S("side_effect"), S("chest tube,surgery,observation"), ValueAtom("infection,pneumonia")))
    metta.space().add_atom(E(S("symptom"), S("heartburn,regurgitation,chest pain"), S("GERD")))
    metta.space().add_atom(E(S("treatment"), S("GERD"), ValueAtom("omeprazole,lifestyle changes,fundoplication")))
    metta.space().add_atom(E(S("side_effect"), S("omeprazole,lifestyle changes,fundoplication"), ValueAtom("osteoporosis,vitamin B12 deficiency")))
    metta.space().add_atom(E(S("symptom"), S("abdominal pain,nausea,fever"), S("appendicitis")))
    metta.space().add_atom(E(S("treatment"), S("appendicitis"), ValueAtom("appendectomy,antibiotics,pain management")))
    metta.space().add_atom(E(S("side_effect"), S("appendectomy,antibiotics,pain management"), ValueAtom("surgical complications,antibiotic resistance")))
    metta.space().add_atom(E(S("symptom"), S("severe abdominal pain,nausea,vomiting"), S("gallstones")))
    metta.space().add_atom(E(S("treatment"), S("gallstones"), ValueAtom("cholecystectomy,ursodeoxycholic acid,dietary changes")))
    metta.space().add_atom(E(S("side_effect"), S("cholecystectomy,ursodeoxycholic acid,dietary changes"), ValueAtom("diarrhea,bile duct injury")))
    metta.space().add_atom(E(S("symptom"), S("abdominal pain,back pain,weight loss"), S("pancreatitis")))
    metta.space().add_atom(E(S("treatment"), S("pancreatitis"), ValueAtom("pain management,enzyme replacement,surgery")))
    metta.space().add_atom(E(S("side_effect"), S("pain management,enzyme replacement,surgery"), ValueAtom("addiction risk,malabsorption")))
    metta.space().add_atom(E(S("symptom"), S("yellowing skin,dark urine,fatigue"), S("hepatitis")))
    metta.space().add_atom(E(S("treatment"), S("hepatitis"), ValueAtom("antivirals,rest,vaccination")))
    metta.space().add_atom(E(S("side_effect"), S("antivirals,rest,vaccination"), ValueAtom("flu-like symptoms,injection site reaction")))
    metta.space().add_atom(E(S("symptom"), S("weight loss,excessive hunger,blurred vision"), S("type 2 diabetes")))
    metta.space().add_atom(E(S("treatment"), S("type 2 diabetes"), ValueAtom("metformin,insulin,lifestyle modification")))
    metta.space().add_atom(E(S("side_effect"), S("metformin,insulin,lifestyle modification"), ValueAtom("lactic acidosis,hypoglycemia")))
    metta.space().add_atom(E(S("symptom"), S("heat intolerance,weight loss,rapid heartbeat"), S("hyperthyroidism")))
    metta.space().add_atom(E(S("treatment"), S("hyperthyroidism"), ValueAtom("methimazole,radioactive iodine,beta-blockers")))
    metta.space().add_atom(E(S("side_effect"), S("methimazole,radioactive iodine,beta-blockers"), ValueAtom("agranulocytosis,hypothyroidism")))
    metta.space().add_atom(E(S("symptom"), S("moon face,weight gain,high blood pressure"), S("Cushing syndrome")))
    metta.space().add_atom(E(S("treatment"), S("Cushing syndrome"), ValueAtom("surgery,ketoconazole,radiation")))
    metta.space().add_atom(E(S("side_effect"), S("surgery,ketoconazole,radiation"), ValueAtom("adrenal insufficiency,liver toxicity")))
    metta.space().add_atom(E(S("symptom"), S("darkening skin,salt craving,weakness"), S("Addison disease")))
    metta.space().add_atom(E(S("treatment"), S("Addison disease"), ValueAtom("hydrocortisone,fludrocortisone,salt replacement")))
    metta.space().add_atom(E(S("side_effect"), S("hydrocortisone,fludrocortisone,salt replacement"), ValueAtom("osteoporosis,hypertension")))
    metta.space().add_atom(E(S("symptom"), S("excessive growth,enlarged features,joint pain"), S("acromegaly")))
    metta.space().add_atom(E(S("treatment"), S("acromegaly"), ValueAtom("surgery,octreotide,pegvisomant")))
    metta.space().add_atom(E(S("side_effect"), S("surgery,octreotide,pegvisomant"), ValueAtom("diabetes,gallstones")))
    metta.space().add_atom(E(S("symptom"), S("muscle cramps,weakness,numbness"), S("electrolyte imbalance")))
    metta.space().add_atom(E(S("treatment"), S("electrolyte imbalance"), ValueAtom("IV fluids,potassium,magnesium")))
    metta.space().add_atom(E(S("side_effect"), S("IV fluids,potassium,magnesium"), ValueAtom("fluid overload,arrhythmia")))
    metta.space().add_atom(E(S("symptom"), S("burning feet,numbness,tingling"), S("diabetic neuropathy")))
    metta.space().add_atom(E(S("treatment"), S("diabetic neuropathy"), ValueAtom("gabapentin,duloxetine,topical lidocaine")))
    metta.space().add_atom(E(S("side_effect"), S("gabapentin,duloxetine,topical lidocaine"), ValueAtom("dizziness,dry mouth")))
    metta.space().add_atom(E(S("symptom"), S("eye pain,blurred vision,halos"), S("glaucoma")))
    metta.space().add_atom(E(S("treatment"), S("glaucoma"), ValueAtom("timolol,laser surgery,trabeculectomy")))
    metta.space().add_atom(E(S("side_effect"), S("timolol,laser surgery,trabeculectomy"), ValueAtom("bradycardia,infection")))
    metta.space().add_atom(E(S("symptom"), S("cloudy vision,glare sensitivity,halos"), S("cataracts")))
    metta.space().add_atom(E(S("treatment"), S("cataracts"), ValueAtom("cataract surgery,intraocular lens,eye drops")))
    metta.space().add_atom(E(S("side_effect"), S("cataract surgery,intraocular lens,eye drops"), ValueAtom("infection,retinal detachment")))
    metta.space().add_atom(E(S("symptom"), S("hearing loss,tinnitus,dizziness"), S("Meniere disease")))
    metta.space().add_atom(E(S("treatment"), S("Meniere disease"), ValueAtom("diuretics,betahistine,surgery")))
    metta.space().add_atom(E(S("side_effect"), S("diuretics,betahistine,surgery"), ValueAtom("dehydration,hearing loss")))
    metta.space().add_atom(E(S("symptom"), S("recurrent infections,easy bruising,fatigue"), S("leukemia")))
    metta.space().add_atom(E(S("treatment"), S("leukemia"), ValueAtom("chemotherapy,bone marrow transplant,radiation")))
    metta.space().add_atom(E(S("side_effect"), S("chemotherapy,bone marrow transplant,radiation"), ValueAtom("immunosuppression,graft-versus-host disease")))
    metta.space().add_atom(E(S("symptom"), S("enlarged lymph nodes,night sweats,weight loss"), S("lymphoma")))
    metta.space().add_atom(E(S("treatment"), S("lymphoma"), ValueAtom("chemotherapy,immunotherapy,stem cell transplant")))
    metta.space().add_atom(E(S("side_effect"), S("chemotherapy,immunotherapy,stem cell transplant"), ValueAtom("neuropathy,secondary cancers")))
    metta.space().add_atom(E(S("symptom"), S("skin changes,irregular mole,itching"), S("melanoma")))
    metta.space().add_atom(E(S("treatment"), S("melanoma"), ValueAtom("surgical excision,immunotherapy,targeted therapy")))
    metta.space().add_atom(E(S("side_effect"), S("surgical excision,immunotherapy,targeted therapy"), ValueAtom("scarring,autoimmune reactions")))
    metta.space().add_atom(E(S("symptom"), S("pelvic pain,heavy bleeding,bloating"), S("ovarian cancer")))
    metta.space().add_atom(E(S("treatment"), S("ovarian cancer"), ValueAtom("surgery,carboplatin,paclitaxel")))
    metta.space().add_atom(E(S("side_effect"), S("surgery,carboplatin,paclitaxel"), ValueAtom("neuropathy,hearing loss")))
    metta.space().add_atom(E(S("symptom"), S("difficulty urinating,blood in urine,pelvic pain"), S("prostate cancer")))
    metta.space().add_atom(E(S("treatment"), S("prostate cancer"), ValueAtom("surgery,radiation,hormone therapy")))
    metta.space().add_atom(E(S("side_effect"), S("surgery,radiation,hormone therapy"), ValueAtom("incontinence,erectile dysfunction")))
    metta.space().add_atom(E(S("symptom"), S("sore throat,difficulty swallowing,fever"), S("strep throat")))
    metta.space().add_atom(E(S("treatment"), S("strep throat"), ValueAtom("penicillin,throat lozenges,rest")))
    metta.space().add_atom(E(S("side_effect"), S("penicillin,throat lozenges,rest"), ValueAtom("allergic reaction,stomach upset")))
    metta.space().add_atom(E(S("symptom"), S("ear pain,hearing loss,discharge"), S("ear infection")))
    metta.space().add_atom(E(S("treatment"), S("ear infection"), ValueAtom("amoxicillin,ear drops,pain relievers")))
    metta.space().add_atom(E(S("side_effect"), S("amoxicillin,ear drops,pain relievers"), ValueAtom("diarrhea,ear irritation")))
    metta.space().add_atom(E(S("symptom"), S("red eyes,itching,discharge"), S("conjunctivitis")))
    metta.space().add_atom(E(S("treatment"), S("conjunctivitis"), ValueAtom("antibiotic drops,warm compress,antihistamines")))
    metta.space().add_atom(E(S("side_effect"), S("antibiotic drops,warm compress,antihistamines"), ValueAtom("eye irritation,drowsiness")))
    metta.space().add_atom(E(S("symptom"), S("stuffy nose,sneezing,watery eyes"), S("hay fever")))
    metta.space().add_atom(E(S("treatment"), S("hay fever"), ValueAtom("loratadine,nasal spray,avoidance")))
    metta.space().add_atom(E(S("side_effect"), S("loratadine,nasal spray,avoidance"), ValueAtom("dry mouth,nasal irritation")))
    metta.space().add_atom(E(S("symptom"), S("skin rash,itching,redness"), S("eczema")))
    metta.space().add_atom(E(S("treatment"), S("eczema"), ValueAtom("topical steroids,moisturizers,antihistamines")))
    metta.space().add_atom(E(S("side_effect"), S("topical steroids,moisturizers,antihistamines"), ValueAtom("skin thinning,drowsiness")))
    metta.space().add_atom(E(S("symptom"), S("dandruff,itchy scalp,flaking"), S("seborrheic dermatitis")))
    metta.space().add_atom(E(S("treatment"), S("seborrheic dermatitis"), ValueAtom("antifungal shampoo,selenium sulfide,ketoconazole")))
    metta.space().add_atom(E(S("side_effect"), S("antifungal shampoo,selenium sulfide,ketoconazole"), ValueAtom("scalp irritation,hair discoloration")))
    metta.space().add_atom(E(S("symptom"), S("acne,blackheads,oily skin"), S("acne vulgaris")))
    metta.space().add_atom(E(S("treatment"), S("acne vulgaris"), ValueAtom("benzoyl peroxide,tretinoin,doxycycline")))
    metta.space().add_atom(E(S("side_effect"), S("benzoyl peroxide,tretinoin,doxycycline"), ValueAtom("skin dryness,sun sensitivity")))
    metta.space().add_atom(E(S("symptom"), S("warts,skin growths,rough texture"), S("common warts")))
    metta.space().add_atom(E(S("treatment"), S("common warts"), ValueAtom("cryotherapy,salicylic acid,laser removal")))
    metta.space().add_atom(E(S("side_effect"), S("cryotherapy,salicylic acid,laser removal"), ValueAtom("scarring,skin discoloration")))
    metta.space().add_atom(E(S("symptom"), S("athlete foot,itching,peeling"), S("tinea pedis")))
    metta.space().add_atom(E(S("treatment"), S("tinea pedis"), ValueAtom("antifungal cream,powder,good hygiene")))
    metta.space().add_atom(E(S("side_effect"), S("antifungal cream,powder,good hygiene"), ValueAtom("skin irritation")))
    metta.space().add_atom(E(S("symptom"), S("ringworm,circular rash,scaling"), S("tinea corporis")))
    metta.space().add_atom(E(S("treatment"), S("tinea corporis"), ValueAtom("antifungal cream,oral antifungals,hygiene")))
    metta.space().add_atom(E(S("side_effect"), S("antifungal cream,oral antifungals,hygiene"), ValueAtom("liver toxicity,skin reaction")))
    metta.space().add_atom(E(S("symptom"), S("cold sores,lip blisters,tingling"), S("herpes simplex")))
    metta.space().add_atom(E(S("treatment"), S("herpes simplex"), ValueAtom("acyclovir,valacyclovir,topical cream")))
    metta.space().add_atom(E(S("side_effect"), S("acyclovir,valacyclovir,topical cream"), ValueAtom("nausea,headache")))
    metta.space().add_atom(E(S("symptom"), S("chickenpox,itchy blisters,fever"), S("varicella")))
    metta.space().add_atom(E(S("treatment"), S("varicella"), ValueAtom("calamine lotion,antihistamines,rest")))
    metta.space().add_atom(E(S("side_effect"), S("calamine lotion,antihistamines,rest"), ValueAtom("drowsiness,skin dryness")))
    metta.space().add_atom(E(S("symptom"), S("shingles,burning pain,rash"), S("herpes zoster")))
    metta.space().add_atom(E(S("treatment"), S("herpes zoster"), ValueAtom("acyclovir,gabapentin,topical lidocaine")))
    metta.space().add_atom(E(S("side_effect"), S("acyclovir,gabapentin,topical lidocaine"), ValueAtom("dizziness,skin numbness")))
    metta.space().add_atom(E(S("symptom"), S("impetigo,honey crusted lesions,itching"), S("impetigo")))
    metta.space().add_atom(E(S("treatment"), S("impetigo"), ValueAtom("topical antibiotics,oral antibiotics,hygiene")))
    metta.space().add_atom(E(S("side_effect"), S("topical antibiotics,oral antibiotics,hygiene"), ValueAtom("antibiotic resistance,allergic reaction")))
    metta.space().add_atom(E(S("symptom"), S("cellulitis,skin swelling,warmth"), S("cellulitis")))
    metta.space().add_atom(E(S("treatment"), S("cellulitis"), ValueAtom("antibiotics,elevation,warm compress")))
    metta.space().add_atom(E(S("side_effect"), S("antibiotics,elevation,warm compress"), ValueAtom("C diff infection,skin burns")))
    metta.space().add_atom(E(S("symptom"), S("boil,painful lump,pus"), S("furuncle")))
    metta.space().add_atom(E(S("treatment"), S("furuncle"), ValueAtom("warm compress,incision drainage,antibiotics")))
    metta.space().add_atom(E(S("side_effect"), S("warm compress,incision drainage,antibiotics"), ValueAtom("scarring,recurrence")))
    metta.space().add_atom(E(S("symptom"), S("sunburn,red skin,pain"), S("solar dermatitis")))
    metta.space().add_atom(E(S("treatment"), S("solar dermatitis"), ValueAtom("aloe vera,cool compress,ibuprofen")))
    metta.space().add_atom(E(S("side_effect"), S("aloe vera,cool compress,ibuprofen"), ValueAtom("allergic reaction,stomach upset")))
    metta.space().add_atom(E(S("symptom"), S("poison ivy,itching,blisters"), S("contact dermatitis")))
    metta.space().add_atom(E(S("treatment"), S("contact dermatitis"), ValueAtom("topical steroids,antihistamines,cool baths")))
    metta.space().add_atom(E(S("side_effect"), S("topical steroids,antihistamines,cool baths"), ValueAtom("skin atrophy,drowsiness")))
    metta.space().add_atom(E(S("symptom"), S("insect bite,swelling,itching"), S("insect bite reaction")))
    metta.space().add_atom(E(S("treatment"), S("insect bite reaction"), ValueAtom("antihistamines,topical steroids,ice")))
    metta.space().add_atom(E(S("side_effect"), S("antihistamines,topical steroids,ice"), ValueAtom("drowsiness,skin irritation")))
    metta.space().add_atom(E(S("symptom"), S("hives,raised welts,itching"), S("urticaria")))
    metta.space().add_atom(E(S("treatment"), S("urticaria"), ValueAtom("antihistamines,epinephrine,avoidance")))
    metta.space().add_atom(E(S("side_effect"), S("antihistamines,epinephrine,avoidance"), ValueAtom("sedation,anxiety")))
    metta.space().add_atom(E(S("symptom"), S("indigestion,bloating,stomach pain"), S("dyspepsia")))
    metta.space().add_atom(E(S("treatment"), S("dyspepsia"), ValueAtom("antacids,diet modification,proton pump inhibitors")))
    metta.space().add_atom(E(S("side_effect"), S("antacids,diet modification,proton pump inhibitors"), ValueAtom("constipation,nutrient deficiency")))
    metta.space().add_atom(E(S("symptom"), S("constipation,hard stool,straining"), S("constipation")))
    metta.space().add_atom(E(S("treatment"), S("constipation"), ValueAtom("fiber supplements,laxatives,increased fluids")))
    metta.space().add_atom(E(S("side_effect"), S("fiber supplements,laxatives,increased fluids"), ValueAtom("bloating,electrolyte imbalance")))
    metta.space().add_atom(E(S("symptom"), S("diarrhea,loose stool,urgency"), S("diarrhea")))
    metta.space().add_atom(E(S("treatment"), S("diarrhea"), ValueAtom("oral rehydration,BRAT diet,loperamide")))
    metta.space().add_atom(E(S("side_effect"), S("oral rehydration,BRAT diet,loperamide"), ValueAtom("constipation,bloating")))
    metta.space().add_atom(E(S("symptom"), S("hemorrhoids,rectal pain,bleeding"), S("hemorrhoids")))
    metta.space().add_atom(E(S("treatment"), S("hemorrhoids"), ValueAtom("topical creams,sitz baths,fiber")))
    metta.space().add_atom(E(S("side_effect"), S("topical creams,sitz baths,fiber"), ValueAtom("skin irritation,gas")))
    metta.space().add_atom(E(S("symptom"), S("lactose intolerance,bloating,diarrhea"), S("lactose intolerance")))
    metta.space().add_atom(E(S("treatment"), S("lactose intolerance"), ValueAtom("lactase supplements,dairy avoidance,probiotics")))
    metta.space().add_atom(E(S("side_effect"), S("lactase supplements,dairy avoidance,probiotics"), ValueAtom("calcium deficiency,gas")))
    metta.space().add_atom(E(S("symptom"), S("irritable bowel,cramping,alternating stool"), S("IBS")))
    metta.space().add_atom(E(S("treatment"), S("IBS"), ValueAtom("fiber,antispasmodics,probiotics")))
    metta.space().add_atom(E(S("side_effect"), S("fiber,antispasmodics,probiotics"), ValueAtom("gas,drowsiness")))
    metta.space().add_atom(E(S("symptom"), S("peptic ulcer,stomach pain,nausea"), S("peptic ulcer")))
    metta.space().add_atom(E(S("treatment"), S("peptic ulcer"), ValueAtom("proton pump inhibitors,antibiotics,bismuth")))
    metta.space().add_atom(E(S("side_effect"), S("proton pump inhibitors,antibiotics,bismuth"), ValueAtom("C diff infection,black stool")))
    metta.space().add_atom(E(S("symptom"), S("motion sickness,nausea,vomiting"), S("motion sickness")))
    metta.space().add_atom(E(S("treatment"), S("motion sickness"), ValueAtom("dramamine,scopolamine patch,ginger")))
    metta.space().add_atom(E(S("side_effect"), S("dramamine,scopolamine patch,ginger"), ValueAtom("drowsiness,dry mouth")))
    metta.space().add_atom(E(S("symptom"), S("hiccups,spasms,discomfort"), S("hiccups")))
    metta.space().add_atom(E(S("treatment"), S("hiccups"), ValueAtom("breath holding,sugar,chlorpromazine")))
    metta.space().add_atom(E(S("side_effect"), S("breath holding,sugar,chlorpromazine"), ValueAtom("sedation,tardive dyskinesia")))
    metta.space().add_atom(E(S("symptom"), S("belching,gas,bloating"), S("excessive gas")))
    metta.space().add_atom(E(S("treatment"), S("excessive gas"), ValueAtom("simethicone,diet changes,probiotics")))
    metta.space().add_atom(E(S("side_effect"), S("simethicone,diet changes,probiotics"), ValueAtom("")))
    metta.space().add_atom(E(S("symptom"), S("bad breath,halitosis,oral odor"), S("halitosis")))
    metta.space().add_atom(E(S("treatment"), S("halitosis"), ValueAtom("oral hygiene,mouthwash,dental cleaning")))
    metta.space().add_atom(E(S("side_effect"), S("oral hygiene,mouthwash,dental cleaning"), ValueAtom("mouth irritation,tooth sensitivity")))
    metta.space().add_atom(E(S("symptom"), S("tooth decay,cavity pain,sensitivity"), S("dental caries")))
    metta.space().add_atom(E(S("treatment"), S("dental caries"), ValueAtom("dental filling,fluoride,root canal")))
    metta.space().add_atom(E(S("side_effect"), S("dental filling,fluoride,root canal"), ValueAtom("tooth sensitivity,fluorosis")))
    metta.space().add_atom(E(S("symptom"), S("gum disease,bleeding gums,swelling"), S("gingivitis")))
    metta.space().add_atom(E(S("treatment"), S("gingivitis"), ValueAtom("professional cleaning,antibacterial mouthwash,flossing")))
    metta.space().add_atom(E(S("side_effect"), S("professional cleaning,antibacterial mouthwash,flossing"), ValueAtom("tooth sensitivity,mouth irritation")))
    metta.space().add_atom(E(S("symptom"), S("canker sore,mouth ulcer,pain"), S("aphthous ulcer")))
    metta.space().add_atom(E(S("treatment"), S("aphthous ulcer"), ValueAtom("topical analgesics,mouth rinse,avoidance triggers")))
    metta.space().add_atom(E(S("side_effect"), S("topical analgesics,mouth rinse,avoidance triggers"), ValueAtom("temporary numbness,taste alteration")))
    metta.space().add_atom(E(S("symptom"), S("dry mouth,xerostomia,difficulty swallowing"), S("xerostomia")))
    metta.space().add_atom(E(S("treatment"), S("xerostomia"), ValueAtom("artificial saliva,sugar-free gum,hydration")))
    metta.space().add_atom(E(S("side_effect"), S("artificial saliva,sugar-free gum,hydration"), ValueAtom("gastrointestinal upset")))
    metta.space().add_atom(E(S("symptom"), S("toothache,dental pain,throbbing"), S("toothache")))
    metta.space().add_atom(E(S("treatment"), S("toothache"), ValueAtom("ibuprofen,clove oil,dental treatment")))
    metta.space().add_atom(E(S("side_effect"), S("ibuprofen,clove oil,dental treatment"), ValueAtom("stomach upset,mouth numbness")))
    metta.space().add_atom(E(S("symptom"), S("wisdom tooth pain,jaw swelling,difficulty opening"), S("impacted wisdom tooth")))
    metta.space().add_atom(E(S("treatment"), S("impacted wisdom tooth"), ValueAtom("extraction,pain medication,antibiotics")))
    metta.space().add_atom(E(S("side_effect"), S("extraction,pain medication,antibiotics"), ValueAtom("dry socket,addiction risk")))
    metta.space().add_atom(E(S("symptom"), S("TMJ pain,jaw clicking,headache"), S("TMJ disorder")))
    metta.space().add_atom(E(S("treatment"), S("TMJ disorder"), ValueAtom("mouth guard,physical therapy,muscle relaxants")))
    metta.space().add_atom(E(S("side_effect"), S("mouth guard,physical therapy,muscle relaxants"), ValueAtom("jaw soreness,drowsiness")))
    metta.space().add_atom(E(S("symptom"), S("teeth grinding,jaw pain,worn teeth"), S("bruxism")))
    metta.space().add_atom(E(S("treatment"), S("bruxism"), ValueAtom("night guard,stress management,muscle relaxants")))
    metta.space().add_atom(E(S("side_effect"), S("night guard,stress management,muscle relaxants"), ValueAtom("jaw discomfort,sedation")))
    metta.space().add_atom(E(S("symptom"), S("back pain,stiffness,muscle spasm"), S("lower back pain")))
    metta.space().add_atom(E(S("treatment"), S("lower back pain"), ValueAtom("NSAIDs,physical therapy,heat therapy")))
    metta.space().add_atom(E(S("side_effect"), S("NSAIDs,physical therapy,heat therapy"), ValueAtom("stomach irritation,muscle soreness")))
    metta.space().add_atom(E(S("symptom"), S("neck pain,stiffness,headache"), S("neck strain")))
    metta.space().add_atom(E(S("treatment"), S("neck strain"), ValueAtom("muscle relaxants,massage,ice")))
    metta.space().add_atom(E(S("side_effect"), S("muscle relaxants,massage,ice"), ValueAtom("drowsiness,skin irritation")))
    metta.space().add_atom(E(S("symptom"), S("shoulder pain,limited movement,weakness"), S("rotator cuff injury")))
    metta.space().add_atom(E(S("treatment"), S("rotator cuff injury"), ValueAtom("physical therapy,cortisone injection,surgery")))
    metta.space().add_atom(E(S("side_effect"), S("physical therapy,cortisone injection,surgery"), ValueAtom("temporary weakness,infection")))
    metta.space().add_atom(E(S("symptom"), S("tennis elbow,elbow pain,grip weakness"), S("lateral epicondylitis")))
    metta.space().add_atom(E(S("treatment"), S("lateral epicondylitis"), ValueAtom("rest,NSAIDs,elbow strap")))
    metta.space().add_atom(E(S("side_effect"), S("rest,NSAIDs,elbow strap"), ValueAtom("muscle weakness,skin irritation")))
    metta.space().add_atom(E(S("symptom"), S("carpal tunnel,wrist pain,numbness"), S("carpal tunnel syndrome")))
    metta.space().add_atom(E(S("treatment"), S("carpal tunnel syndrome"), ValueAtom("wrist splint,steroid injection,surgery")))
    metta.space().add_atom(E(S("side_effect"), S("wrist splint,steroid injection,surgery"), ValueAtom("muscle weakness,infection")))
    metta.space().add_atom(E(S("symptom"), S("knee pain,swelling,stiffness"), S("knee osteoarthritis")))
    metta.space().add_atom(E(S("treatment"), S("knee osteoarthritis"), ValueAtom("NSAIDs,physical therapy,knee injection")))
    metta.space().add_atom(E(S("side_effect"), S("NSAIDs,physical therapy,knee injection"), ValueAtom("gastric bleeding,joint infection")))
    metta.space().add_atom(E(S("symptom"), S("ankle sprain,swelling,bruising"), S("ankle sprain")))
    metta.space().add_atom(E(S("treatment"), S("ankle sprain"), ValueAtom("RICE,NSAIDs,ankle brace")))
    metta.space().add_atom(E(S("side_effect"), S("RICE,NSAIDs,ankle brace"), ValueAtom("skin maceration,stomach upset")))
    metta.space().add_atom(E(S("symptom"), S("plantar fasciitis,heel pain,morning stiffness"), S("plantar fasciitis")))
    metta.space().add_atom(E(S("treatment"), S("plantar fasciitis"), ValueAtom("stretching,orthotics,steroid injection")))
    metta.space().add_atom(E(S("side_effect"), S("stretching,orthotics,steroid injection"), ValueAtom("muscle soreness,plantar fascia rupture")))
    metta.space().add_atom(E(S("symptom"), S("muscle cramp,sudden pain,muscle tightness"), S("muscle cramp")))
    metta.space().add_atom(E(S("treatment"), S("muscle cramp"), ValueAtom("stretching,massage,electrolyte replacement")))
    metta.space().add_atom(E(S("side_effect"), S("stretching,massage,electrolyte replacement"), ValueAtom("muscle soreness")))
    metta.space().add_atom(E(S("symptom"), S("muscle strain,pain,swelling"), S("muscle strain")))
    metta.space().add_atom(E(S("treatment"), S("muscle strain"), ValueAtom("rest,ice,compression")))
    metta.space().add_atom(E(S("side_effect"), S("rest,ice,compression"), ValueAtom("muscle weakness,skin irritation")))
    metta.space().add_atom(E(S("symptom"), S("bruise,discoloration,tenderness"), S("contusion")))
    metta.space().add_atom(E(S("treatment"), S("contusion"), ValueAtom("ice,elevation,pain relievers")))
    metta.space().add_atom(E(S("side_effect"), S("ice,elevation,pain relievers"), ValueAtom("frostbite,stomach upset")))
    metta.space().add_atom(E(S("symptom"), S("sciatica,leg pain,numbness"), S("sciatica")))
    metta.space().add_atom(E(S("treatment"), S("sciatica"), ValueAtom("NSAIDs,physical therapy,epidural injection")))
    metta.space().add_atom(E(S("side_effect"), S("NSAIDs,physical therapy,epidural injection"), ValueAtom("GI bleeding,nerve damage")))
    metta.space().add_atom(E(S("symptom"), S("whiplash,neck pain,headache"), S("whiplash")))
    metta.space().add_atom(E(S("treatment"), S("whiplash"), ValueAtom("cervical collar,physical therapy,muscle relaxants")))
    metta.space().add_atom(E(S("side_effect"), S("cervical collar,physical therapy,muscle relaxants"), ValueAtom("muscle weakness,dependency")))
    metta.space().add_atom(E(S("symptom"), S("bursitis,joint swelling,pain"), S("bursitis")))
    metta.space().add_atom(E(S("treatment"), S("bursitis"), ValueAtom("rest,NSAIDs,steroid injection")))
    metta.space().add_atom(E(S("side_effect"), S("rest,NSAIDs,steroid injection"), ValueAtom("muscle atrophy,joint infection")))
    metta.space().add_atom(E(S("symptom"), S("tendinitis,tendon pain,swelling"), S("tendinitis")))
    metta.space().add_atom(E(S("treatment"), S("tendinitis"), ValueAtom("rest,ice,physical therapy")))
    metta.space().add_atom(E(S("side_effect"), S("rest,ice,physical therapy"), ValueAtom("muscle weakness,stiffness")))
    metta.space().add_atom(E(S("symptom"), S("bunion,big toe pain,deformity"), S("bunion")))
    metta.space().add_atom(E(S("treatment"), S("bunion"), ValueAtom("proper footwear,bunion pad,surgery")))
    metta.space().add_atom(E(S("side_effect"), S("proper footwear,bunion pad,surgery"), ValueAtom("discomfort,infection")))
    metta.space().add_atom(E(S("symptom"), S("hammer toe,toe deformity,pain"), S("hammer toe")))
    metta.space().add_atom(E(S("treatment"), S("hammer toe"), ValueAtom("toe splint,proper shoes,surgery")))
    metta.space().add_atom(E(S("side_effect"), S("toe splint,proper shoes,surgery"), ValueAtom("skin irritation,stiffness")))
    metta.space().add_atom(E(S("symptom"), S("ingrown nail,toe pain,swelling"), S("ingrown toenail")))
    metta.space().add_atom(E(S("treatment"), S("ingrown toenail"), ValueAtom("soaking,proper trimming,nail removal")))
    metta.space().add_atom(E(S("side_effect"), S("soaking,proper trimming,nail removal"), ValueAtom("infection,recurrence")))
    metta.space().add_atom(E(S("symptom"), S("callus,thick skin,foot pain"), S("callus")))
    metta.space().add_atom(E(S("treatment"), S("callus"), ValueAtom("pumice stone,moisturizer,proper footwear")))
    metta.space().add_atom(E(S("side_effect"), S("pumice stone,moisturizer,proper footwear"), ValueAtom("skin irritation")))
    metta.space().add_atom(E(S("symptom"), S("corn,painful bump,pressure"), S("corn")))
    metta.space().add_atom(E(S("treatment"), S("corn"), ValueAtom("corn pad,salicylic acid,debridement")))
    metta.space().add_atom(E(S("side_effect"), S("corn pad,salicylic acid,debridement"), ValueAtom("skin irritation,infection")))
    metta.space().add_atom(E(S("symptom"), S("menstrual cramps,pelvic pain,heavy bleeding"), S("dysmenorrhea")))
    metta.space().add_atom(E(S("treatment"), S("dysmenorrhea"), ValueAtom("NSAIDs,hormonal contraceptives,heat")))
    metta.space().add_atom(E(S("side_effect"), S("NSAIDs,hormonal contraceptives,heat"), ValueAtom("nausea,blood clots")))
    metta.space().add_atom(E(S("symptom"), S("yeast infection,vaginal itching,discharge"), S("vaginal candidiasis")))
    metta.space().add_atom(E(S("treatment"), S("vaginal candidiasis"), ValueAtom("antifungal cream,fluconazole,probiotics")))
    metta.space().add_atom(E(S("side_effect"), S("antifungal cream,fluconazole,probiotics"), ValueAtom("vaginal irritation,liver toxicity")))
    metta.space().add_atom(E(S("symptom"), S("UTI,burning urination,frequency"), S("cystitis")))
    metta.space().add_atom(E(S("treatment"), S("cystitis"), ValueAtom("antibiotics,cranberry juice,hydration")))
    metta.space().add_atom(E(S("side_effect"), S("antibiotics,cranberry juice,hydration"), ValueAtom("antibiotic resistance,stomach upset")))
    metta.space().add_atom(E(S("symptom"), S("BV,fishy odor,discharge"), S("bacterial vaginosis")))
    metta.space().add_atom(E(S("treatment"), S("bacterial vaginosis"), ValueAtom("metronidazole,clindamycin,probiotics")))
    metta.space().add_atom(E(S("side_effect"), S("metronidazole,clindamycin,probiotics"), ValueAtom("metallic taste,diarrhea")))
    metta.space().add_atom(E(S("symptom"), S("PMS,mood changes,bloating"), S("premenstrual syndrome")))
    metta.space().add_atom(E(S("symptom"), S("chest pain"), S("diabetes+lung cancer+pneumonia")))
    metta.space().add_atom(E(S("symptom"), S("chest pain"), S("diabetes+lung cancer+pneumonia")))
    metta.space().add_atom(E(S("symptom"), S("chest pain"), S("diabetes+lung cancer+pneumonia")))
    metta.space().add_atom(E(S("symptom"), S("chest pain"), S("diabetes+lung cancer+pneumonia")))
    metta.space().add_atom(E(S("symptom"), S("chest pain"), S("diabetes+lung cancer+pneumonia")))
